-- =====================================================================
--  DINAMIK AKADEMIK TAKVIM SISTEMI - VERITABANI SEMASI (PostgreSQL)
--  Bu betik uygulama her acilista calisir; bu yuzden tamamen idempotent
--  (IF NOT EXISTS) yazilmistir.
-- =====================================================================

-- ---------------------------------------------------------------------
-- BIRIM: Fakulte / Enstitu / MYO ve "Universite Geneli" kaydi
--
-- TASARIM NOTU: Arayuzdeki "Genel Takvim" secenegi de bir birim satiridir
-- (tur = 'GENEL'). Boylece "birim bilgisi bos birakilamaz" is kurali
-- veritabani seviyesinde NOT NULL ile zorlanabilir.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS birim (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad              VARCHAR(150) NOT NULL,
    kod             VARCHAR(50)  NOT NULL UNIQUE,
    tur             VARCHAR(20)  NOT NULL,
    aktif           BOOLEAN      NOT NULL DEFAULT TRUE,
    olusturma_zamani TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT birim_tur_gecerli CHECK (tur IN ('GENEL', 'FAKULTE', 'ENSTITU', 'MYO', 'YUKSEKOKUL'))
);

-- ---------------------------------------------------------------------
-- KATEGORI: Etkinlik turleri (Ders ve Sinav, Kayit ve Basvuru, ...)
-- Super Admin panelden yenisini ekleyebilir -> kod degisikligi gerekmez.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kategori (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad              VARCHAR(100) NOT NULL,
    kod             VARCHAR(50)  NOT NULL UNIQUE,
    renk            VARCHAR(7)   NOT NULL DEFAULT '#64748B',   -- Arayuzde rozet rengi (#RRGGBB)
    sira            INTEGER      NOT NULL DEFAULT 0,
    aktif           BOOLEAN      NOT NULL DEFAULT TRUE,
    olusturma_zamani TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kategori_renk_gecerli CHECK (renk ~ '^#[0-9A-Fa-f]{6}$')
);

-- ---------------------------------------------------------------------
-- EGITIM_YILI: "2025-2026" gibi. Pasif yil yeni kayitta secilemez.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS egitim_yili (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad              VARCHAR(20) NOT NULL UNIQUE,
    baslangic_tarihi DATE       NOT NULL,
    bitis_tarihi    DATE        NOT NULL,
    aktif           BOOLEAN     NOT NULL DEFAULT TRUE,
    olusturma_zamani TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT egitim_yili_tarih_sirasi CHECK (bitis_tarihi >= baslangic_tarihi)
);

-- ---------------------------------------------------------------------
-- KULLANICI: Sifreler BCrypt ile hashlenmis olarak saklanir.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kullanici (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_adi   VARCHAR(60)  NOT NULL UNIQUE,
    sifre_hash      VARCHAR(100) NOT NULL,
    ad_soyad        VARCHAR(120) NOT NULL,
    eposta          VARCHAR(150),
    rol             VARCHAR(30)  NOT NULL,
    aktif           BOOLEAN      NOT NULL DEFAULT TRUE,
    son_giris       TIMESTAMP,
    olusturma_zamani TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kullanici_rol_gecerli CHECK (rol IN ('SUPER_ADMIN', 'BIRIM_YONETICISI'))
);

-- ---------------------------------------------------------------------
-- KULLANICI_BIRIM: Birim Yoneticisi <-> sorumlu oldugu birim(ler)
-- Super Admin'in burada kaydi olmaz; o zaten her birime erisir.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kullanici_birim (
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id) ON DELETE CASCADE,
    birim_id     BIGINT NOT NULL REFERENCES birim(id)     ON DELETE CASCADE,
    PRIMARY KEY (kullanici_id, birim_id)
);

-- ---------------------------------------------------------------------
-- ETKINLIK: Sistemin ana tablosu
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS etkinlik (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad               VARCHAR(250) NOT NULL,
    aciklama         TEXT,                                    -- Istege bagli; PDF ciktisina DAHIL EDILMEZ
    baslangic_tarihi DATE         NOT NULL,
    bitis_tarihi     DATE         NOT NULL,
    donem            VARCHAR(10)  NOT NULL,
    egitim_yili_id   BIGINT       NOT NULL REFERENCES egitim_yili(id),
    kategori_id      BIGINT       NOT NULL REFERENCES kategori(id),
    birim_id         BIGINT       NOT NULL REFERENCES birim(id),
    olusturan        VARCHAR(60),
    guncelleyen      VARCHAR(60),
    olusturma_zamani TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    guncelleme_zamani TIMESTAMP,
    -- IS KURALI 2: bitis tarihi baslangictan once olamaz (servis katmaninda da dogrulanir)
    CONSTRAINT etkinlik_tarih_sirasi CHECK (bitis_tarihi >= baslangic_tarihi),
    CONSTRAINT etkinlik_donem_gecerli CHECK (donem IN ('GUZ', 'BAHAR', 'YAZ'))
);

-- IS KURALI 5: etkinlikler kronolojik listelenir -> tarih indeksi zorunlu
CREATE INDEX IF NOT EXISTS ix_etkinlik_baslangic   ON etkinlik (baslangic_tarihi);
CREATE INDEX IF NOT EXISTS ix_etkinlik_birim       ON etkinlik (birim_id);
CREATE INDEX IF NOT EXISTS ix_etkinlik_kategori    ON etkinlik (kategori_id);
CREATE INDEX IF NOT EXISTS ix_etkinlik_egitim_yili ON etkinlik (egitim_yili_id);
-- Ana ekranin en sik sorgusu: egitim yili + birim, tarihe gore sirali
CREATE INDEX IF NOT EXISTS ix_etkinlik_filtre      ON etkinlik (egitim_yili_id, birim_id, baslangic_tarihi);

-- ---------------------------------------------------------------------
-- ISLEM_KAYDI (Audit Log)
--
-- TASARIM NOTU: hedef_id bilerek FOREIGN KEY DEGILDIR.
-- Is analizi: "Kayit veritabanindan kaldirilir, ancak islem gecmisinde
-- silme kaydi tutulur." FK olsaydi etkinlik silinince ya log da silinir
-- ya da silme engellenirdi. Silinen kaydin tum alanlari eski_deger
-- (JSONB) kolonunda saklanir.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS islem_kaydi (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_adi VARCHAR(60)  NOT NULL,
    islem_turu    VARCHAR(20)  NOT NULL,
    hedef_tur     VARCHAR(40)  NOT NULL,   -- 'ETKINLIK', 'BIRIM', 'KATEGORI', ...
    hedef_id      BIGINT,                  -- FK DEGIL (yukaridaki nota bakiniz)
    hedef_ozet    VARCHAR(250),            -- Insan okuyabilsin diye kisa ozet
    eski_deger    JSONB,
    yeni_deger    JSONB,
    ip_adresi     VARCHAR(45),             -- IPv6 sigacak uzunluk
    islem_zamani  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT islem_turu_gecerli CHECK (islem_turu IN ('EKLE', 'GUNCELLE', 'SIL', 'ICE_AKTAR'))
);

CREATE INDEX IF NOT EXISTS ix_islem_kaydi_zaman  ON islem_kaydi (islem_zamani DESC);
CREATE INDEX IF NOT EXISTS ix_islem_kaydi_hedef  ON islem_kaydi (hedef_tur, hedef_id);
